language: go
go: 
 - 1.5
 - 1.6
 - 1.7
 - tip
before_install:
 - go get -t -v
 - go get github.com/axw/gocov/gocov
 - go get github.com/mattn/goveralls
 - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
 - go test -v ./...
 - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken=$COVERALLS